name: fitcker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0-14.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  introduction_screen: ^3.1.17
  uuid: ^4.5.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1 
  http: ^1.5.0
  go_router: ^16.1.0
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.6
  freezed: ^3.1.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
